server:
  port: 10010

spring:
  application:
    name: leyou-geteway

#注册中心配置项
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    # 从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
    registry-fetch-interval-seconds: 5

# 网关配置项
zuul:
  prefix: /api  # 添加路由前缀
  routes:
    item-service: /item/**  # 将商品微服务映射到/item/**