# eureka端口
server:
  port: 10086

# 注册的名字.相当于bean。唯一标识之类的。如果没有eureka会默认unknow。
spring:
  application:
    name: leyou-registy

# eureka 配置
eureka:
  client:
    service-url:
      # 可用区域映射到与eureka服务器通信的完全限定URL列表。每个值可以是单个URL或逗号分隔的备用位置列表。(http://${eureka.instance.hostname}:${server.port}/eureka/)
      defaultZone: http://localhost:${server.port}/eureka
      # 指示此实例是否应将其信息注册到eureka服务器以供其他服务发现，默认为false
    register-with-eureka: false
      # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    fetch-registry: false
  server:
    # 客户端是否获取eureka服务器注册表上的注册信息，默认为true
    enable-self-preservation: false
    # eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒。
    eviction-interval-timer-in-ms: 10000

#